// Coverage data for different insurance types and plans

export const coverageData: Record<
  string,
  Record<
    string,
    {
      planId: string;
      planName: string;
      description: string;
      price: number;
      excess: string;
      allRiskCap: string;
      covered: string[];
      notCovered: string[];
    }
  >
> = {
  "tenant-policy": {
    basic: {
      planId: "basic",
      planName: "Basic Plan",
      description: "Perfect for protection for you and up to content",
      price: 26275,
      excess: "₦20,000 or 10% of claim",
      allRiskCap: "Up to ₦300,000",
      covered: [
        "Household contents up to ₦5,000,000",
        "Accidental damage up to ₦2,000,000",
        "All-risks extension up to ₦500,000 (jewellery, gadgets)",
        "Personal accident up to ₦1,500,000",
        "Alternative accommodation up to ₦500,000",
      ],
      notCovered: [
        "Building structure",
        "Negligence or deliberate damage",
        "Wear and tear",
        "Undeclared high-value items",
        "War or terrorism losses",
      ],
    },
    bronze: {
      planId: "bronze",
      planName: "Bronze Plan",
      description: "Better coverage for your home, contents and small gadgets",
      price: 49775,
      excess: "₦30,000 or 10% of claim",
      allRiskCap: "Up to ₦500,000",
      covered: [
        
        "Household contents up to ₦10,000,000",
        "Accidental damage up to ₦4,000,000",
        "All-risks extension up to ₦1,000,000 (jewellery, gadgets, electronics)",
        "Personal accident up to ₦1,500,000",
        "Alternative accommodation up to ₦1,500,000",
       
      ],
      notCovered: [
        "Building structure",
        "Negligence or deliberate damage",
        "Wear and tear",
        "Undeclared high-value items",
        "War or terrorism losses",
      ],
    },
    silver: {
      planId: "silver",
      planName: "Silver Plan",
      description: "Best balance of affordability and complete protection",
      price: 96775,
      excess: "₦50,000 or 10% of claim",
      allRiskCap: "Up to ₦1,000,000",
      covered: [
        
        "Household contents up to ₦20,000,000",
        "Accidental damage up to ₦8,000,000",
        "All-risks extension up to ₦2,000,000 (jewellery, gadgets, electronics, artwork)",
        "Personal accident up to ₦1,500,000",
        "Alternative accommodation up to ₦1,500,000",
       
      ],
      notCovered: [
        "Building structure",
        "Negligence or deliberate damage",
        "Wear and tear",
        "Undeclared high-value items",
        "War or terrorism losses",
       
      ],
    },
    gold: {
      planId: "gold",
      planName: "Gold Plan",
      description: "Provides even with higher limits for valuables and more",
      price: 143775,
      excess: "₦75,000 or 10% of claim",
      allRiskCap: "Up to ₦3,000,000",
      covered: [
       
        "Household contents up to ₦30,000,000",
        "Accidental damage up to ₦12,000,000",
        "All-risks extension up to ₦3,000,000 (jewellery, gadgets, electronics, artwork, collectibles)",
        "Personal accident up to ₦1,500,000",
        "Alternative accommodation up to ₦1,500,000",
       
      ],
      notCovered: [
        "Building structure",
        "Negligence or deliberate damage",
        "Wear and tear",
        "Undeclared high-value items",
        "War or terrorism losses",
      ],
    },
    platinum: {
      planId: "platinum",
      planName: "Platinum Plan",
      description: "All-round protection for high-value homes and possessions",
      price: 237775,
      excess: "₦100,000 or 10% of claim",
      allRiskCap: "Up to ₦5,000,000",
      covered: [
        "Household contents up to ₦50,000,000",
        "Accidental damage up to ₦20,000,000",
        "All-risks extension up to ₦5,000,000 (jewellery, gadgets, electronics, artwork, collectibles)",
        "Personal accident up to ₦1,500,000",
        "Alternative accommodation up to ₦5,000,000",
      
      ],
      notCovered: [
        "Building structure",
       "Negligence or deliberate damage",
        "Wear and tear",
        "Undeclared high-value items",
        "War or terrorism losses",
      ],
    },
  },
  "homeowner-policy": {
    basic: {
      planId: "basic",
      planName: "Basic Plan",
      description: "Essential coverage for homeowners",
      price: 89000,
      excess: "₦50,000 or 10% of claim",
      allRiskCap: "Up to ₦500,000",
      covered: [
        "Building structure up to ₦50,000,000",
        "Contents up to ₦10,000,000",
        "Accidental damage coverage",
        "Third-party liability protection",
        "Fire and lightning coverage",
        "Burglary and theft protection",
      ],
      notCovered: [
        "Maintenance and repairs",
        "Negligence or deliberate damage",
        "Wear and tear",
        "War or terrorism losses",
        "Claims from unlawful activities",
      ],
    },
    bronze: {
      planId: "bronze",
      planName: "Bronze Plan",
      description: "Comprehensive homeowner protection",
      price: 156000,
      excess: "₦40,000 or 8% of claim",
      allRiskCap: "Up to ₦800,000",
      covered: [
        "Building structure up to ₦75,000,000",
        "Contents up to ₦15,000,000",
        "Accidental damage coverage",
        "Third-party liability up to ₦5,000,000",
        "Fire and lightning coverage",
        "Burglary and theft protection",
        "Storm and flooding coverage",
        "Subsidence coverage",
      ],
      notCovered: [
        "Maintenance and repairs",
        "Negligence or deliberate damage",
        "Wear and tear",
        "War or terrorism losses",
        "Claims from unlawful activities",
      ],
    },
    silver: {
      planId: "silver",
      planName: "Silver Plan",
      description: "Premium homeowner coverage",
      price: 267000,
      excess: "₦30,000 or 6% of claim",
      allRiskCap: "Up to ₦1,200,000",
      covered: [
        "Building structure up to ₦100,000,000",
        "Contents up to ₦25,000,000",
        "Accidental damage coverage",
        "Third-party liability up to ₦10,000,000",
        "Fire and lightning coverage",
        "Burglary and theft protection",
        "Storm and flooding coverage",
        "Subsidence and ground instability",
        "Renewable energy systems coverage",
        "Loss of rent coverage",
      ],
      notCovered: [
        "Maintenance and repairs",
        "Negligence or deliberate damage",
        "Wear and tear",
        "War or terrorism losses",
      ],
    },
    gold: {
      planId: "gold",
      planName: "Gold Plan",
      description: "Elite homeowner protection",
      price: 445000,
      excess: "₦20,000 or 4% of claim",
      allRiskCap: "Up to ₦1,500,000",
      covered: [
        "Building structure up to ₦150,000,000",
        "Contents up to ₦40,000,000",
        "Accidental damage coverage",
        "Third-party liability up to ₦20,000,000",
        "Fire and lightning coverage",
        "Burglary and theft protection",
        "Storm and flooding coverage",
        "Subsidence and ground instability",
        "Renewable energy systems coverage",
        "Loss of rent coverage",
        "Worldwide coverage for contents",
        "24/7 emergency response",
        "Dedicated claims support",
      ],
      notCovered: [
        "Maintenance and repairs",
        "Claims from unlawful activities",
      ],
    },
    platinum: {
      planId: "platinum",
      planName: "Platinum Plan",
      description: "Ultimate homeowner protection",
      price: 712000,
      excess: "No excess clause",
      allRiskCap: "Unlimited",
      covered: [
        "Building structure - Unlimited coverage",
        "Contents - Unlimited coverage",
        "Full accidental damage coverage",
        "Third-party liability - Unlimited",
        "All perils coverage",
        "Worldwide coverage for contents",
        "Renewable energy systems - Full coverage",
        "Loss of rent - Unlimited",
        "24/7 priority claims handling",
        "Dedicated claims manager",
        "Home reconstruction with original materials",
        "Contents replacement at new value",
        "Concierge and assistance services",
      ],
      notCovered: ["Claims from unlawful activities"],
    },
  },
  "landlord-policy": {
    basic: {
      planId: "basic",
      planName: "Basic Plan",
      description: "Essential landlord protection",
      price: 125000,
      excess: "₦40,000 or 8% of claim",
      allRiskCap: "Up to ₦600,000",
      covered: [
        "Building structure up to ₦60,000,000",
        "Loss of rent up to ₦2,000,000",
        "Accidental damage coverage",
        "Third-party liability up to ₦5,000,000",
        "Fire and lightning coverage",
        "Burglary and theft protection",
        "Malicious damage coverage",
      ],
      notCovered: [
        "Rent from defaulting tenants",
        "Tenant's personal belongings",
        "Wear and tear",
        "War or terrorism losses",
      ],
    },
    bronze: {
      planId: "bronze",
      planName: "Bronze Plan",
      description: "Comprehensive landlord coverage",
      price: 195000,
      excess: "₦30,000 or 6% of claim",
      allRiskCap: "Up to ₦900,000",
      covered: [
        "Building structure up to ₦80,000,000",
        "Loss of rent up to ₦3,000,000",
        "Accidental damage coverage",
        "Third-party liability up to ₦10,000,000",
        "Fire and lightning coverage",
        "Burglary and theft protection",
        "Malicious damage coverage",
        "Storm and weather damage",
        "Subsidence coverage",
      ],
      notCovered: [
        "Rent from defaulting tenants",
        "Tenant's personal belongings",
        "Wear and tear",
        "War or terrorism losses",
      ],
    },
    silver: {
      planId: "silver",
      planName: "Silver Plan",
      description: "Premium landlord protection",
      price: 325000,
      excess: "₦20,000 or 4% of claim",
      allRiskCap: "Up to ₦1,200,000",
      covered: [
        "Building structure up to ₦120,000,000",
        "Loss of rent up to ₦5,000,000",
        "Accidental damage coverage",
        "Third-party liability up to ₦15,000,000",
        "Fire and lightning coverage",
        "Burglary and theft protection",
        "Malicious damage coverage",
        "Storm and weather damage",
        "Subsidence and ground instability",
        "Rental guarantee protection",
      ],
      notCovered: [
        "Rent from defaulting tenants (covered under rental guarantee)",
        "Tenant's personal belongings",
        "Wear and tear",
      ],
    },
    gold: {
      planId: "gold",
      planName: "Gold Plan",
      description: "Elite landlord protection",
      price: 520000,
      excess: "₦10,000 or 2% of claim",
      allRiskCap: "Up to ₦1,500,000",
      covered: [
        "Building structure up to ₦200,000,000",
        "Loss of rent - Unlimited",
        "Accidental damage coverage",
        "Third-party liability - Unlimited",
        "All perils coverage",
        "Rental guarantee protection - Unlimited",
        "Legal expenses for eviction",
        "24/7 emergency support",
        "Dedicated claims manager",
      ],
      notCovered: ["Tenant's personal belongings", "War or terrorism losses"],
    },
    platinum: {
      planId: "platinum",
      planName: "Platinum Plan",
      description: "Ultimate landlord protection",
      price: 845000,
      excess: "No excess clause",
      allRiskCap: "Unlimited",
      covered: [
        "Building structure - Unlimited coverage",
        "Loss of rent - Unlimited",
        "Full accidental damage coverage",
        "Third-party liability - Unlimited",
        "All perils coverage",
        "Rental guarantee - Unlimited",
        "Legal expenses - Unlimited",
        "Eviction costs - Covered",
        "24/7 priority support",
        "Dedicated property manager",
        "Tenant vetting services",
        "Home reconstruction with premium materials",
      ],
      notCovered: ["War or terrorism losses"],
    },
  },
};
